"""Add JenkinsBuild model.

Revision ID: 5905f9161c5e
Revises: 10f6231ed2ba
Create Date: 2021-12-29 08:41:35.940329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5905f9161c5e'
down_revision = '10f6231ed2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenkins_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCESS', 'UNSTABLE', 'FAILURE', 'NOT_BUILT', 'ABORTED', name='buildstatus'), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'number', name='unique_build')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jenkins_builds')
    # ### end Alembic commands ###
