"""Added black_status, test_coverage, pep8_violations, pylint_violations, commit, commit_message to JenkinsBuild model

Revision ID: 7adf58c84d91
Revises: 5905f9161c5e
Create Date: 2021-12-31 11:47:21.719491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adf58c84d91'
down_revision = '5905f9161c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jenkins_builds', sa.Column('black_status', sa.Boolean(), nullable=True))
    op.add_column('jenkins_builds', sa.Column('test_coverage', sa.Float(), nullable=True))
    op.add_column('jenkins_builds', sa.Column('pep8_violations', sa.Integer(), nullable=True))
    op.add_column('jenkins_builds', sa.Column('pylint_violations', sa.Integer(), nullable=True))
    op.add_column('jenkins_builds', sa.Column('commit', sa.String(length=40), nullable=True))
    op.add_column('jenkins_builds', sa.Column('commit_message', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_jenkins_builds_site_id'), 'jenkins_builds', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jenkins_builds_site_id'), table_name='jenkins_builds')
    op.drop_column('jenkins_builds', 'commit_message')
    op.drop_column('jenkins_builds', 'commit')
    op.drop_column('jenkins_builds', 'pylint_violations')
    op.drop_column('jenkins_builds', 'pep8_violations')
    op.drop_column('jenkins_builds', 'test_coverage')
    op.drop_column('jenkins_builds', 'black_status')
    # ### end Alembic commands ###
