"""Changed black_status column to Text

Revision ID: c6b7ee0c39d3
Revises: b84bcd3dd10c
Create Date: 2026-01-28 20:56:45.778297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b7ee0c39d3'
down_revision = 'b84bcd3dd10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jenkins_builds', 'black_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)
    op.execute("UPDATE jenkins_builds SET black_status = '' WHERE black_status = 'true'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE jenkins_builds SET black_status = 'true' WHERE black_status = ''")
    op.alter_column('jenkins_builds', 'black_status',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
